export const FETCHING_BOOKS_DATA = "FETCHING_BOOKS_DATA";
export const FETCHING_BOOKS_DATA_SUCCESS = "FETCHING_BOOKS_DATA_SUCCESS";
export const FETCHING_BOOKS_DATA_FAILURE = "FETCHING_BOOKS_DATA_FAILURE";
export const FETCHING_BIBLE_DATA = "FETCHING_BIBLE_DATA";
export const FETCHING_BIBLE_DATA_SUCCESS = "FETCHING_BIBLE_DATA_SUCCESS";
export const FETCHING_BIBLE_DATA_FAILURE = "FETCHING_BIBLE_DATA_FAILURE";
export const UPDATE_UNMOUNT_STATE = "UPDATE_UNMOUNT_STATE";
export const FETCHING_FAVORITES_DATA = "FETCHING_FAVORITES_DATA";
export const FETCHING_FAVORITES_DATA_SUCCESS = "FETCHING_FAVORITES_DATA_SUCCESS";
export const FETCHING_FAVORITES_DATA_FAILURE = "FETCHING_FAVORITES_DATA_FAILURE";
export const FETCHING_SEARCH_DATA = "FETCHING_SEARCH_DATA";
export const FETCHING_SEARCH_DATA_SUCCESS = "FETCHING_SEARCH_DATA_SUCCESS";
export const FETCHING_SEARCH_DATA_FAILURE = "FETCHING_SEARCH_DATA_FAILURE";
export const FETCH_DATA_STATUS = "FETCH_DATA_STATUS";
export const FETCHING_SEARCH_HISTORY_DATA_SUCCESS = "FETCHING_SEARCH_HISTORY_DATA_SUCCESS";

